package remotize

import (
	"bytes"
	"fmt"
	"os"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"reflect"
	"sort"
	"strings"
	"template"
)

// Remotized source code template
const wrapsrc = `// Autogenerated Remotize Interface ${Iface} wrapper [DO NOT EDIT!]
package ${Pack}

import (
${Imports}
)

// Autoregistry
func init() {
	${Prefix}Register(${Iface}Client{},${Iface}Server{})
}

// RPC server exported interface
type ${Iface}RPCs struct {
	s *${Iface}Server
}

// Server wrapper for ${Iface}
type ${Iface}Server struct {
	ServerBase
	Rpcs	*${Iface}RPCs
}

// Bind service
func (s *${Iface}Server) Bind(server *rpc.Server, impl interface{}) {
	s.Base().Bind(server,impl)
	s.Rpcs = &${Iface}RPCs{s}
	server.Register(s.Rpcs)
}

// Local Remote Interface reference
type ${Iface}Remoted struct {
	c *${Iface}Client
}

// Client wrapper for ${Iface}
type ${Iface}Client struct {
	${Prefix}ClientBase
}

// Bind client
func (c *${Iface}Client) Bind(client *rpc.Client) {
	c.Base().Bind(client)
	c.remote = &${Iface}Remoted{c}
}

${Calls}
`

// Autoremotizer template
const autoremotizer = `// Autogenerated Autoremotized [DO NOT EDIT!]
package main

import (
${Imports}
)

var toremotize = []remotize.RemotizeSpec{
${RemotizeList}
}

func main() {
	for _,r := range toremotize {
		if e:=remotize.Remotize(r); e!=nil {
			panic(e)
		}
	}
}
`

// methodInfo for code generation
type methodInfo struct {
	m    methodSpec
	re   bool
	pos  int
	ptrs []int
}

// wrapper infor for code generation
type wrapgen struct {
	Iface   string
	Pack    string
	Prefix  string
	Imports *bytes.Buffer
	Calls   *bytes.Buffer
	imports []string
	methods []methodInfo
}

// remotize info
type RemotizeSpec struct {
	Iface interface{}
	Pos   *token.Position
}

// Remotize will create the rpc client/server file needed to use some given 
// interface remotely
func Remotize(iface interface{}) os.Error {
	ri, ok := (iface).(RemotizeSpec)
	if ok {
		if _, ok := ri.Iface.(string); !ok {
			return Remotize(ri.Iface)
		}
		fset := token.NewFileSet()
		file, e := parser.ParseFile(fset, ri.Pos.Filename, nil, parser.ParseComments)
		if e != nil {
			return e
		}
		var tspec *ast.TypeSpec
		ast.Inspect(file, func(n ast.Node) bool {
			if n != nil && fset.Position(n.Pos()).Offset == ri.Pos.Offset {
				tspec = n.(*ast.TypeSpec)
				return false
			}
			return true
		})
		if it, ok := (tspec.Type).(*ast.InterfaceType); ok {
			return remotize(NewSrcIfaceSpec(tspec.Name.Name, file.Name.Name, it))
		}
	}
	if it := reflect.TypeOf(iface); it.Kind() == reflect.Interface {
		return remotize(&rtIfaceSpec{it})
	}
	t := reflect.TypeOf(iface)
	if pt := t; pt.Kind() == reflect.Ptr {
		if it := pt.Elem(); it.Kind() == reflect.Interface {
			return remotize(&rtIfaceSpec{it})
		}
	}
	msg := fmt.Sprintf("Can't remotize %v of type %v", iface, t)
	return os.NewError(msg)
}

// build generates a program to remotize the detected interfaces
func build(r *rinfo) os.Error {
	imports := []string{"go/token", "remotize"}
	sort.SortStrings(imports)
	r.Imports = bytes.NewBuffer(make([]byte, 0))
	for _, s := range imports {
		fmt.Fprintf(r.Imports, "\"%v\"\n", s)
	}
	src := bytes.NewBuffer(make([]byte, 0))
	r.RemotizeList = bytes.NewBuffer(make([]byte, 0))
	t := template.New(nil)
	t.SetDelims("${", "}")
	e := t.Parse(autoremotizer)
	if e != nil {
		return e
	}
	for name, pos := range r.items {
		var s string
		if pos.src {
			s = "\"" + name + "\""
		} else {
			s = name
		}
		fmt.Fprintf(r.RemotizeList, "{%v, &token.Position{\"%v\",%v,%v,%v}},",
			s, pos.Filename, pos.Offset, pos.Line, pos.Column)
	}
	t.Execute(src, r)
	fset := token.NewFileSet()
	filename := "_autoremotized.go"
	f, e := parser.ParseFile(fset, filename, src, parser.ParseComments)
	if e != nil {
		fmt.Println(src)
		return e
	}
	fos, e := os.Create(filename)
	if e != nil {
		return e
	}
	pcfg := &printer.Config{printer.TabIndent, 2}
	pcfg.Fprint(fos, fset, f)
	fos.Close()
	return nil
}

// interface specficication
type ifaceSpec interface {
	Name() string
	PkgPath() string
	NumMethod() int
	MethodSpec(int) methodSpec
}

// runtime interface specification
type rtIfaceSpec struct {
	reflect.Type
}

// MethodSpec returns the runtime method spec from runtime interface spec
func (is *rtIfaceSpec) MethodSpec(i int) methodSpec {
	return &rtMethodSpec{is.Method(i), nil}
}

// source interface specification
type srcIfaceSpec struct {
	name string
	pack string
	*ast.InterfaceType
}

// sortable fields implement sort.Interface
type SortableFields struct {
	f []*ast.Field
}

func (sf *SortableFields) Len() int {
	return len(sf.f)
}

func (sf *SortableFields) Less(i, j int) bool {
	return solveName(sf.f[i].Names[0]) < solveName(sf.f[j].Names[0])
}

func (sf *SortableFields) Swap(i, j int) {
	f := sf.f[i]
	sf.f[i] = sf.f[j]
	sf.f[j] = f
}

// NewSrcIfaceSpec generates a source interface specification from source code
func NewSrcIfaceSpec(name, pack string, it *ast.InterfaceType) *srcIfaceSpec {
	sis := &srcIfaceSpec{name, pack, it}
	sf := &SortableFields{it.Methods.List}
	sort.Sort(sf)
	return sis
}

func (is *srcIfaceSpec) Name() string {
	return is.name
}

func (is *srcIfaceSpec) PkgPath() string {
	return is.pack
}

func (is *srcIfaceSpec) NumMethod() int {
	return len(is.Methods.List)
}

func (is *srcIfaceSpec) MethodSpec(i int) methodSpec {
	m := is.Methods.List[i]
	return &srcMethodSpec{solveName(m.Names[0]), (m.Type).(*ast.FuncType)}
}

// method specification
type methodSpec interface {
	MethodName() string
	NumIn() int
	InName(int) string
	InElem(int) string
	InPkg(int) string
	InIsPtr(int) bool
	NumOut() int
	OutName(int) string
	OutPkg(int) string
	OutIsError(int) bool
}

// runtime method specification
type rtMethodSpec struct {
	reflect.Method
	errorType reflect.Type
}

func (m *rtMethodSpec) MethodName() string {
	return m.Name
}

func (m *rtMethodSpec) NumIn() int {
	return m.Type.NumIn()
}

func (m *rtMethodSpec) InName(i int) string {
	return m.Type.In(i).String()
}

func (m *rtMethodSpec) InElem(i int) string {
	return m.Type.In(i).Elem().String()
}

func (m *rtMethodSpec) InPkg(i int) string {
	return m.Type.In(i).PkgPath()
}

func (m *rtMethodSpec) InIsPtr(i int) bool {
	return m.Type.In(i).Kind() == reflect.Ptr
}

func (m *rtMethodSpec) NumOut() int {
	return m.Type.NumOut()
}

func (m *rtMethodSpec) OutName(i int) string {
	return m.Type.Out(i).String()
}

func (m *rtMethodSpec) OutPkg(i int) string {
	return m.Type.Out(i).PkgPath()
}

func (m *rtMethodSpec) OutIsError(i int) bool {
	if m.errorType == nil {
		m.errorType = reflect.TypeOf((*os.Error)(nil)).Elem()
	}
	return m.Type.Out(i) == m.errorType
}

// source method specification
type srcMethodSpec struct {
	name string
	*ast.FuncType
}

func (m *srcMethodSpec) MethodName() string {
	return m.name
}

func (m *srcMethodSpec) NumIn() int {
	return len(m.Params.List)
}

func (m *srcMethodSpec) InName(i int) string {
	return solveName(m.Params.List[i])
}

func (m *srcMethodSpec) InElem(i int) string {
	s := m.InName(i)
	if strings.Index(s, "*") == 0 {
		return s[1:]
	}
	return s
}

func (m *srcMethodSpec) InPkg(i int) string {
	s := m.InName(i)
	if i := strings.Index(s, "."); i > 0 {
		return s[0:i]
	}
	return ""
}

func (m *srcMethodSpec) InIsPtr(i int) bool {
	s := m.InName(i)
	return strings.Index(s, "*") == 0
}

func (m *srcMethodSpec) NumOut() int {
	if m.Results == nil {
		return 0
	}
	return len(m.Results.List)
}

func (m *srcMethodSpec) OutName(i int) string {
	//ast.Print(token.NewFileSet(),m.Results.List[i])
	return solveName(m.Results.List[i])
}

func (m *srcMethodSpec) OutPkg(i int) string {
	s := m.OutName(i)
	if j := strings.Index(s, "."); j > 0 {
		return s[0:j]
	}
	return ""
}

func (m *srcMethodSpec) OutIsError(i int) bool {
	return m.OutName(i) == "os.Error"
}

// remotize will remotize the interface by generating 
// the proper rpc client/server wrapping
func remotize(is ifaceSpec) os.Error {
	fmt.Println("Remotizing interface", is.Name())
	w := newWrapgen(is.Name(), is.PkgPath())

	nm := is.NumMethod()
	fmt.Println("Interface exports", nm, "methods")
	for i := 0; i < nm; i++ {
		m := is.MethodSpec(i)
		w.addMethod(m)
	}
	fmt.Println("Generating wrapper...")
	return w.genWrapper(is.Name())
}

// newWrapgen creates an interface wrapper generator
func newWrapgen(Ifacename, pack string) *wrapgen {
	w := &wrapgen{Iface: Ifacename,
		Pack:    pack,
		Calls:   bytes.NewBuffer(make([]byte, 0)),
		imports: []string{"os", "rpc"},
	}
	if pack != "remotize" {
		w.imports = append(w.imports, "remotize")
		w.Prefix = "remotize."
	} else {
		w.Prefix = ""
	}
	return w
}

// addMethod wraps another method from the interface
func (w *wrapgen) addMethod(m methodSpec) {
	re, pos := returnsError(m)
	ptrs := inouts(m)
	nin := m.NumIn()
	for i := 0; i < nin; i++ {
		w.addImport(m.InPkg(i))
	}
	nout := m.NumOut()
	for i := 0; i < nout; i++ {
		w.addImport(m.OutPkg(i))
	}
	w.methods = append(w.methods, methodInfo{m, re, pos, ptrs})
	w.clientWrapper()
	w.serverWrapper()
}

// addImport adds an import if needed
func (w *wrapgen) addImport(imp string) {
	if imp == "" { // empty should not be imported
		return
	}
	for _, i := range w.imports {
		if i == imp { // already imported
			return
		}
	}
	w.imports = append(w.imports, imp)
}

// genWrapper generates the final source code for the wrapped interface
func (w *wrapgen) genWrapper(name string) os.Error {
	sort.SortStrings(w.imports)
	w.Imports = bytes.NewBuffer(make([]byte, 0))
	for _, s := range w.imports {
		fmt.Fprintf(w.Imports, "\"%v\"\n", s)
	}
	src := bytes.NewBuffer(make([]byte, 0))
	t := template.New(nil)
	t.SetDelims("${", "}")
	e := t.Parse(wrapsrc)
	if e != nil {
		fmt.Println("Error parsing source:\n" + wrapsrc)
		return e
	}
	t.Execute(src, w)
	fset := token.NewFileSet()
	filename := strings.ToLower(name) + "Remotized.go"
	f, e := parser.ParseFile(fset, "", src, parser.ParseComments)
	if e != nil {
		fmt.Printf("Error %v parsing file %v src\n", e, filename)
		fos, e := os.Create(filename + ".dump")
		if e != nil {
			fmt.Println("Error creating file:\n" + filename)
			return e
		}
		fmt.Fprintln(fos, src)
		fos.Close()
		return e
	}
	fos, e := os.Create(filename)
	if e != nil {
		fmt.Println("Error creating file:\n" + filename)
		return e
	}
	pcfg := &printer.Config{printer.TabIndent, 1}
	pcfg.Fprint(fos, fset, f)
	fos.Close()
	return nil
}

// clientWrapper genrates the whole client wrapping method
func (w *wrapgen) clientWrapper() {
	mi := w.methods[len(w.methods)-1]
	w.methodSignature(mi.m)
	fmt.Fprintf(w.Calls, " {\n")
	w.wrapCall(mi)
	w.clientReturn(mi)
	fmt.Fprintf(w.Calls, "}\n\n")
}

// wrapCall wrapps the call to the server RPC
func (w *wrapgen) wrapCall(mi methodInfo) {
	m := mi.m
	r := "r"
	if m.NumOut()+len(mi.ptrs) == 0 {
		r = "_"
	}
	fmt.Fprintf(w.Calls, "\t%v, e := Call(c.c.Base(),\"%vRPCs.%v\",",
		r, w.Iface, m.MethodName())
	nin := m.NumIn()
	for i := 0; i < nin; i++ {
		if i > 0 {
			fmt.Fprintf(w.Calls, ",")
		}
		fmt.Fprintf(w.Calls, " a%v", (i + 1))
	}
	fmt.Fprintf(w.Calls, ")\n")
}

// methodSignature generates the client wrapper method signature
func (w *wrapgen) methodSignature(m methodSpec) {
	fmt.Fprintf(w.Calls, "// %v.%v Client wrapper\n", w.Iface, m.MethodName())
	fmt.Fprintf(w.Calls, "func (c *%vRemoted) %v(", w.Iface, m.MethodName())
	nin := m.NumIn()
	for i := 0; i < nin; i++ {
		if i > 0 {
			fmt.Fprintf(w.Calls, ",")
		}
		fmt.Fprintf(w.Calls, "a%v %v", (i + 1), m.InName(i))
	}
	fmt.Fprintf(w.Calls, ")")
	nout := m.NumOut()
	if nout > 0 {
		fmt.Fprintf(w.Calls, " ")
		if nout > 1 {
			fmt.Fprintf(w.Calls, "(")
		}
		for i := 0; i < nout; i++ {
			if i > 0 {
				fmt.Fprintf(w.Calls, ",")
			}
			fmt.Fprintf(w.Calls, "%v", m.OutName(i))
		}
		if nout > 1 {
			fmt.Fprintf(w.Calls, ") ")
		}
	}
}

// clientReturn generates the client wrapper return, including error handling
// if needed
func (w *wrapgen) clientReturn(mi methodInfo) {
	m := mi.m
	if !mi.re {
		fmt.Fprintf(w.Calls, "\tif e != nil {\n")
		fmt.Fprintf(w.Calls, "\t\tHandleError(c.c.Base(),\"%v.%v\", e)\n",
			w.Iface, m.MethodName())
		fmt.Fprintf(w.Calls, "\t}\n")
	}
	nout := m.NumOut()
	ninouts := len(mi.ptrs)
	for i := 0; i < ninouts; i++ {
		fmt.Fprintf(w.Calls, "\t*a%v=(r.R[%v]).(%v)\n", mi.ptrs[i]+1, nout+i,
			m.InElem(mi.ptrs[i]))
	}
	if nout > 0 {
		fmt.Fprintf(w.Calls, "\treturn ")
		for i := 0; i < nout; i++ {
			if i != 0 {
				fmt.Fprintf(w.Calls, ", ")
			}
			if i == mi.pos {
				fmt.Fprintf(w.Calls, "e")
			} else {
				fmt.Fprintf(w.Calls, "(r.R[%v]).(%v)", i, m.OutName(i))
			}
		}
		fmt.Fprintf(w.Calls, "\n")
	}
}

// serverWrapper generates the server call wrapper
func (w *wrapgen) serverWrapper() {
	mi := w.methods[len(w.methods)-1]
	m := mi.m
	fmt.Fprintf(w.Calls, "// %v.%v Server wrapper\n", w.Iface, m.MethodName())
	fmt.Fprintf(w.Calls, "func (s *%vRPCs) %v(", w.Iface, m.MethodName())
	fmt.Fprintf(w.Calls, "a *Args, r *Results) os.Error {\n")
	nout := m.NumOut()
	ninouts := len(mi.ptrs)
	if nout+ninouts > 0 {
		fmt.Fprintf(w.Calls, "\tr.R= make([]interface{}, %v)\n", nout+ninouts)
	}
	for i := 0; i < ninouts; i++ {
		fmt.Fprintf(w.Calls, "\ta%v := (a.A[%v]).(%v)\n", mi.ptrs[i]+1, nout+i,
			m.InElem(mi.ptrs[i]))
		fmt.Fprintf(w.Calls, "\tr.R[%v] = &a%v\n", nout+i, mi.ptrs[i]+1)
	}
	fmt.Fprintf(w.Calls, "\t")
	for i := 0; i < nout; i++ {
		if i != 0 {
			fmt.Fprintf(w.Calls, ", ")
		}
		fmt.Fprintf(w.Calls, "r.R[%v]", i)
	}
	if nout > 0 {
		fmt.Fprintf(w.Calls, " = ")
	}
	fmt.Fprintf(w.Calls, "s.s.impl.(%v).%v(", w.Iface, m.MethodName())
	nin := m.NumIn()
	j := 0
	for i := 0; i < nin; i++ {
		if i != 0 {
			fmt.Fprintf(w.Calls, ", ")
		}
		if j < ninouts && i == mi.ptrs[j] {
			fmt.Fprintf(w.Calls, "(r.R[%v]).(%v)", nout+j, m.InName(mi.ptrs[i]))
			j++
		} else {
			fmt.Fprintf(w.Calls, "(a.A[%v]).(%v)", i, m.InName(i))
		}
	}
	fmt.Fprintf(w.Calls, ")\n")
	if mi.re {
		fmt.Fprintf(w.Calls, "\tif r.R[%v] != nil {\n", mi.pos)
		fmt.Fprintf(w.Calls, "\t\treturn (r.R[%v]).(os.Error)\n", mi.pos)
		fmt.Fprintf(w.Calls, "\t}\n")
	}
	fmt.Fprintf(w.Calls, "\treturn nil\n")
	fmt.Fprintf(w.Calls, "}\n\n")
}

// returnsError says whether a method returns an os.Error and where
func returnsError(m methodSpec) (hasError bool, pos int) {
	nout := m.NumOut()
	for i := 0; i < nout; i++ {
		if m.OutIsError(i) {
			return true, i
		}
	}
	return false, -1
}

// inouts returns an array with the positions (starting at o) of input 
// parameters that are pointers. 
// Those pointers should be treated as input/output parameters
func inouts(m methodSpec) []int {
	nin := m.NumIn()
	ptrs := make([]int, 0)
	for i := 0; i < nin; i++ {
		if m.InIsPtr(i) {
			ptrs = append(ptrs, i)
		}
	}
	return ptrs
}

